import yaml


document = """
  a: 1
  b:
    c: 3
    d: 4
"""

yamlobj = yaml.load(document)
print yamlobj
print yamlobj['a'] 
print yamlobj['b']
print yamlobj['b']['c'] 
yamlobj['b']['c'] = 5
print yamlobj['b']['c'] 
print yamlobj['a'] 

document2= """
invoice: 34843
date   : 2001-01-23
bill-to: &id001
    given  : Chris
    family : Dumars
    address:
        lines: |
            458 Walkman Dr.
            Suite #292
        city    : Royal Oak
        state   : MI
        postal  : 48046
ship-to: *id001
product:
    - sku         : BL394D
      quantity    : 4
      description : Basketball
      price       : 450.00
    - sku         : BL4438H
      quantity    : 1
      description : Super Hoop
      price       : 2392.00
tax  : 251.42
total: 4443.52
comments:
    Late afternoon is best.
    Backup contact is Nancy
    Billsmer @ 338-4338.
    """

yamlobj2 = yaml.load(document2)
print yamlobj2
print "Quantity of First sku", yamlobj2['product'][0]['quantity']
print "Quantity of sencond sku", yamlobj2['product'][1]['quantity']

print "type on yamlobj2 is ", type(yamlobj2)

#below adding one more item to dictionary "Total"
yamlobj2['Total']= yamlobj2['product'][0]['quantity'] * yamlobj2['product'][1]['price']
print yamlobj2

print yaml.dump(yamlobj2) # Print in yaml way

dir(help(yaml.dump))







